name: Android CI

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      # Checkout source code
      - uses: actions/checkout@v3

      # Setup Java (JDK 17)
      - name: Set up JDK 17
        uses: actions/setup-java@v3
        with:
          java-version: '17'
          distribution: 'temurin'
          cache: gradle

      # Grant execute permission untuk gradlew
      - name: Grant execute permission for gradlew
        run: chmod +x gradlew

      # Build APK release
      - name: Build with Gradle
        run: ./gradlew assembleRelease

      # Upload APK (pakai versi terbaru v4
