name: Android CI

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Setup JDK 17
        uses: actions/setup-java@v3
        with:
          java-version: '17'
          distribution: 'temurin'
          cache: gradle

      # Gradle Wrapper permission
      - name: Grant execute permission for gradlew
        run: chmod +x ./gradlew

      # Build Debug APK
      - name: Build Debug APK
        run: ./gradlew assembleDebug --no-daemon

      # Build Release APK (signed)
      - name: Build Release APK
        env:
          KEYSTORE_PASSWORD: ${{ secrets.KEYSTORE_PASSWORD }}
          KEY_PASSWORD: ${{ secrets.KEY_PASSWORD }}
          KEY_ALIAS: ${{ secrets.KEY_ALIAS }}
        run: |
          ./gradlew assembleRelease --no-daemon \
            -Pandroid.injected.signing.store.file=ayiks-release-key.jks \
            -Pandroid.injected.signing.store.password=$KEYSTORE_PASSWORD \
            -Pandroid.injected.signing.key.alias=$KEY_ALIAS \
            -Pandroid.injected.signing.key.password=$KEY_PASSWORD

      # Upload Debug APK ke artifacts
      - name: Upload Debug APK
        uses: actions/upload-artifact@v3
        with:
          name: AYIKS-Debug
          path: app/build/outputs/apk/debug/*.apk

      # Upload Release APK ke artifacts
      - name: Upload Release APK
        uses: actions/upload-artifact@v3
        with:
          name: AYIKS-Release
          path: app/build/outputs/apk/release/*.apk
