name: Android CI

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      # 1. Checkout project
      - name: Checkout project
        uses: actions/checkout@v3

      # 2. Set up JDK 17 (required AGP 8.0.2)
      - name: Set up JDK 17
        uses: actions/setup-java@v3
        with:
          distribution: temurin
          java-version: 17
          cache: gradle

      # 3. Grant execute permission untuk gradlew
      - name: Grant execute permission for gradlew
        run: chmod +x gradlew

      # 4. Cache Gradle dependencies
      - name: Cache Gradle packages
        uses: actions/cache@v3
        with:
          path: |
            ~/.gradle/caches
            ~/.gradle/wrapper
          key: gradle-${{ runner.os }}-${{ hashFiles('**/*.gradle*', '**/gradle-wrapper.properties') }}
          restore-keys: |
            gradle-${{ runner.os }}-

      # 5. Build APK debug
      - name: Build with Gradle
        run: ./gradlew assembleDebug

      # 6. Upload debug APK sebagai artifact
      - name: Upload APK artifact
        uses: actions/upload-artifact@v4
        with:
          name: AYIKS-debug-apk
          path: app/build/outputs/apk/debug/*.apk
